### ISSUE TITLE
IBM functional ID for project

### ISSUE THREAD

**Issue by rayoz12** [Call-for-Code/OpenHarvest#29]
We need a functional ID to represent OpenHarvest in emails and officially when communicating with external parties. Many integrations want need proof that we're from IBM and a functional ID that we can all access is the best way to do that. There are probably some processes to go through internally but it shouldn't be too hard. This will replace the protonmail email we have.

**Comment by Philipsty** [comment]
@rayoz12 could you give a description for this issue please? Asem would like to assist

**Comment by rayoz12** [comment]
Didn't even see the tag.
